echo "**********************************************************"
alias ll="ls -l"
echo "ll.........for ls -l"
alias skynet="cd /opt/skynet/bin"
echo "skynet.....to change dirs"
alias killit="sudo /opt/skynet/bin/killit.sh"
echo "killit.....to kill skynet"
alias startit="sudo /opt/skynet/bin/skynetd.py start"
echo "startit....to start skynet"
alias restartit="sudo /opt/skynet/bin/restart.sh"
echo "restartit..to restart skynet"
