#!/usr/bin/python

def printWebForm():
    print("<h1>SkynetController Thermostat WebIO</h1><br>")
    #HTML OUTPUT
    print("<a href='skynet.py'>Manual Reload</a><br>")
    print("<form id='dc' name='dc' method='post' action='/cgi-bin/skynet.py'>")
    print("  <table width='600' border='1' cellspacing='0' cellpadding='2'>")
    print("    <tr>")
    print("      <th align='center' scope='col'>CHANNEL</th>")
    print("      <th align='center' scope='col'>STATUS/CHANGE</th>")
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_SYSTEM [0]</td>")
    print("      <td align='center'><label><input type='radio' name='relay1' value='off' id='off' {of}/>Off</label><label><input type='radio' name='relay1' value='on' id='on' {on}/>On</label></td>".format(of=relaysOFF[0],on=relaysON[0]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_FAN - [1]</td>")
    print("      <td align='center'><label><input type='radio' name='relay2' value='off' id='off' {of}/>Off</label><label><input type='radio' name='relay2' value='on' id='on' {on}/>On</label></td>".format(of=relaysOFF[1],on=relaysON[1]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_HEAT - [2]</td>")
    print("      <td align='center'><label><input type='radio' name='relay3' value='off' id='off' {of}/>Off</label><label><input type='radio' name='relay3' value='on' id='on' {on}/>On</label></td>".format(of=relaysOFF[2],on=relaysON[2]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_COOL - [3]</td>")
    print("      <td align='center'><label><input type='radio' name='relay4' value='off' id='off' {of}/>Off</label><label><input type='radio' name='relay4' value='on' id='on' {on}/>On</label></td>".format(of=relaysOFF[3],on=relaysON[3]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_AUTO - [4]</td>")
    print("      <td align='center'><label><input type='radio' name='relay5' value='off' id='off' {of}/>Off (Manual)</label><label><input type='radio' name='relay5' value='on' id='on' {on}/>On (Automatic)</label></td>".format(of=relaysOFF[4],on=relaysON[4]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>HVAC_HOME - [5]</td>")
    print("      <td align='center'><label><input type='radio' name='relay6' value='off' id='off' {of}/>Off (Away)</label><label><input type='radio' name='relay6' value='on' id='on' {on}/>On (Home)</label></td>".format(of=relaysOFF[5],on=relaysON[5]))
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>ALL</td>")
    print("      <td align='center'><label><input type='radio' name='allrelays' value='off' id='off' />Off</label><label><input type='radio' name='allrelays' value='on' id='on' />On</label></td>")
    print("    </tr>")
    print("    <tr>")
    print("      <td align='center'>&nbsp;</td>")
    print("      <td align='center'><input type='submit' name='submit' id='submit' value='Submit' /></td>")
    print("    </tr>")
    print("  </table>")
    print("</form>")
